# Add account settings and API keys here.
# This file should be listed in .gitignore to keep your settings secret!
# Each entry gets set as a local environment variable.
# This file overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: 'Your_Gmail_Username'
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# THEN HAVE TO ADD CODE TO /config/application.rb.   see line 62 and beyond.
        # config.before_configuration do
        #   env_file = File.join(Rails.root, 'config', 'local_env.yml')
        #   YAML.load(File.open(env_file)).each do |key, value|
        #     ENV[key.to_s] = value
        #   end if File.exists?(env_file)
        # end



# if you wanted to have different settings per rails environment.... 
if Rails.env.development?
    FACEBOOK_SECRET: '3cb5d23a3b43e4ddd30e2c26162c598d'
    FACEBOOK_APP_ID: '486981084689070'
end

if Rails.env.test?
    FACEBOOK_SECRET: '3cb5d23a3b43e4ddd30e2c26162c598d'
    FACEBOOK_APP_ID: '486981084689070'
end

if Rails.env.production?
    FACEBOOK_SECRET: '77dbee8d35889c3dc64dc7ff97dd673f'
    FACEBOOK_APP_ID: '442524942499942'
end
